#!/bin/bash

timestamp=$(date +%F_%H-%M-%S)
eu4dir=$HOME/.local/share/Paradox\ Interactive/Europa\ Universalis\ IV/save\ games

for f in "$eu4dir"/*.eu4; do
	save=$(basename "$f")
        cp "$f" "$eu4dir"/backups/"$timestamp"_"$save"
done
