#!/bin/bash
card=1

toggle ()
{
  message=`amixer -c ${card} set Mic toggle \
      | grep '\[on\]' > /dev/null \
          && echo 'mic unmuted' \
          || echo 'mic muted'`;


  notify-send "${message}";
  espeak "${message}";
  location=`dirname "$0"`
}

isMuted ()
{
  amixer -c ${card} get Mic | grep '\[off\]' > /dev/null
}

i3block ()
{
  isMuted
  if [[ $? -eq 0 ]]; then
    echo "" # full text
    echo "" # short text
    echo "#FF0000" # colour
  else
    echo "" # full text
    echo "" # short text
    echo "#00FF00" # colour
  fi
}

$1
