#!/bin/bash
path=$(dirname $BASH_SOURCE)

for dir in "$path/config"/*/; do
  name=$(basename "$dir")
  if [[ "$1" != "-y" ]]; then
    read -p "Copy $name to ~/.config/$name? [Y/n] " confirm
    if [[ "$confirm" =~ ^[Nn]$ ]]; then
      echo "Skipped $name."
      continue
    fi
  fi
  cp -RT "$dir" ~/.config/"$name"
  echo "Copied $name."
done
