#!/bin/bash

path=$(realpath $(dirname $BASH_SOURCE))

cp -r $path/bashrc.d $HOME/.bashrc.d
echo created $HOME/.bashrc.d

tee -a $HOME/.bashrc << BASH

if [ -d ~/.bashrc.d ]; then
  for f in ~/.bashrc.d/*; do
    . \$f
  done
fi

BASH
echo appended to $HOME/.bashrc
