#!/bin/bash

set -x

sudo apt update

sudo apt install -y \
	jq \
	git \
	vim \
	i3 \
	i3blocks \
	feh \
	flameshot \
	scrot \
	fonts-font-awesome \
	pavucontrol \
	espeak \
	unrar \
	arandr \
	obs-studio \
	xdotool \
	xclip \
	curl \
	chromium-browser
	

sudo snap install code --classic
sudo snap install	spotify
sudo snap install vlc
