#!/bin/bash

set -x

sudo apt update

sudo apt install -y \
	jq \
	git \
	vim \
	i3 \
	i3blocks \
	feh \
	flameshot \
	scrot \
	fonts-font-awesome \
	pavucontrol \
	espeak \
	unrar \
	arandr \
	obs-studio \
	xdotool \
	xclip \
	curl \
	chromium-browser \
	playerctl

curl -fsSL https://deb.nodesource.com/setup_lts.x | sudo -E bash -
sudo apt-get install -y nodejs
	
sudo snap install code --classic
sudo snap install vlc
